### ISSUE TITLE
branch pushed without version update

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#131]
**Describe the bug**

Updatecli seems to push the branch with only yaml formatting changes... (curse you #89) however it did not create a PR. So now I have this "dead" branch hanging outside of automation part 😓

https://github.com/jetersen/home.cluster/branches

https://github.com/jetersen/home.cluster/runs/1516598146?check_suite_focus=true#step:3:427
https://github.com/jetersen/home.cluster/runs/1516598146?check_suite_focus=true#step:3:1342

**Comment by jetersen** [comment]
Oh, the branch is created but it did not push the yaml indent changes: https://github.com/jetersen/home.cluster/compare/updatecli/kube-prometheus-stackHelmChart/12.7.0 🤣

**Comment by jetersen** [comment]
Seems this is systemic problem as on a second run I got even more branches with no changes.

**Comment by olblak** [comment]
I found the issue, it's a stupid wrong condition. I can fix when I get access to a  computer

**Comment by olblak** [comment]
> I found the issue
I think I found the root cause of the problem which is based on a misunderstanding on my side.
Each time we run git push from updatecli, It doesn't push the current branch but every local branches as explained in doc for [PushOptions](https://pkg.go.dev/github.com/go-git/go-git/v5#PushOptions.RefSpecs) and [Refspec](https://pkg.go.dev/github.com/go-git/go-git/v5@v5.2.0/config#RefSpec)

The problematic code is located [here](https://github.com/olblak/updatecli/blob/master/pkg/plugins/git/generic/main.go#L245L248)

**Comment by olblak** [comment]
This issue has probably be introduced in [v0.0.22](https://github.com/olblak/updatecli/releases/tag/v0.0.22) as before we were always working from a clean directory while need we reuse git repository

**Comment by jetersen** [comment]
much appreciated 🦄

**Comment by olblak** [comment]
> much appreciated unicorn

Thanks for reporting those issues, specifically this one helped me to identify an issue on the jenkins-infra project :)
