### ISSUE TITLE
support updating partial values in cases of kustomize manifests

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#51]
**Is your feature request related to a problem? Please describe.**
In kustomize you can have remote bases with versions like how argo-cd publish their manifest:
```yaml
bases:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.5.7
```

Not sure the current "target" supports targeting a array index and replacing the value.
The source in argo-cd case would be github releases.

**Describe the solution you'd like**

Something like this would work.

```tpl
source:
  kind: githubRelease
  spec:
    owner: "argoproj"
    repository: "argo-cd"
    version: "latest"
targets:
  argocd:
    name: "ArgoCD"
    kind: yaml
    spec:
      file: "kustomize/argo-cd/kustomization.yaml"
      key: bases[0]
      value: https://github.com/argoproj/argo-cd/manifests/cluster-install?ref={{ .version }}
```

**Comment by olblak** [comment]
At the moment, It doesn't support updating targets based on array position.
This something that I started working on but I didn't have the time to finish it yet because of others prioritize.
I waiting for this to release the version [0.0.10](https://github.com/olblak/updatecli/releases/tag/untagged-7e66684dfca033c4d910), It's required in order to have this #47 useful

**Comment by jetersen** [comment]
Do you have branch I could try and work on?

**Comment by olblak** [comment]
Apparently, it's not documented yet but in the current state, you can add postfix or prefix to the value retrieved from the source and then use it in every 'target'. It could make sense to copy those options to target as well in order to only have it by target. 
You just have to add Postfix or Prefix as defined in the code [here](https://github.com/olblak/updatecli/blob/master/pkg/engine/source/main.go#L18L19). 
You can find a working example on the jenkins infrastructure project [here](https://github.com/jenkins-infra/charts/blob/42394172e32eeb49cb131adc62733ec8b2e850d0/updateCli/updateCli.d/jenkins-weekly-jdk11.tpl#L3).

> Do you have branch I could try and work on?

Apparently I didn't work on it as much I thought, I only started writing test cases :panda_face:

But the first thing that I was wondering is the syntax for referencing the position in an array.
`array.1` or `array[1]`. `array.1` can be ambiguous as  `1` could be both the key value name or a position. So I was more thinking to only use the syntax array[1].

The go function that parses and replaces the value is located [here](https://github.com/olblak/updatecli/blob/master/pkg/yaml/main.go#L29L67). As we don't know the yaml schema in advance, it's not trivial to parse yaml files.
I am using this yaml [library](https://pkg.go.dev/gopkg.in/yaml.v3)

**Comment by olblak** [comment]
The replace function is not something that I am really proud of, I wrote it when I had less experience with the yaml library, I have some ideas on how to improve it so I'll handle it

**Comment by jetersen** [comment]
Much appreciated 🙇
